### ISSUE TITLE
Circuit diagram ?

### ISSUE THREAD

**Issue by bengy70** [GrogSym/solarimmersion#1]
Using Home Assistant and would very much like to use your Solarimmersion but struggling a bit with which ESP32 pin goes to which pin on the Dimmer Switch Front Panel.
Circuit Diagram or any help greatly appreciated.

**Comment by GrogSym** [comment]
Hi! You'll see in the esp32yaml file the following:

gate_pin: GPIO25
    zero_cross_pin:
      number: GPIO26

Hope that helps but let me know if you're still stuck.

Greg

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: bengy70 ***@***.***>
Sent: Tuesday, February 20, 2024 3:07:13 pm
To: GrogSym/solarimmersion ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GrogSym/solarimmersion] Circuit diagram ? (Issue #1)


Using Home Assistant and would very much like to use your Solarimmersion but struggling a bit with which ESP32 pin goes to which pin on the Dimmer Switch Front Panel.
Circuit Diagram or any help greatly appreciated.

**Comment by bengy70** [comment]
Hi Greg

Many thanks for your quick reply.

I have ordered my AC dimmer but it has not arrived yet, so just getting my head around the wiring without actually having anything to look at - so, sorry for the questions.
It was the connections to the AC dimmer end I was interested in, as it is not clear to me at the moment what each wire on the front panel of this unit does, or how to work out which SPECIFIC wire at  the display end goes to either GPI025 or GPIO26.
That was the bit I was struggling with, and it is very hard without the unit itself or even a cct diagram of the AC dimmer.
Do you know where I can get a manual for the AC Dimmer prior to its arrival - I am sure that would help !
Any further help from you would be very much appreciated, or should I just wait until the AC Dimmer arrives, and all will  become clear ?
Many thanks

Graham

**Comment by GrogSym** [comment]
If it's exactly the same dimmer it will all become perfectly clear! The names are meaningless to most, but handily are printed on the board and the wires :)

Have fun!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bengy70** [comment]
Hi Greg

Found a picture of the back of the display - I now see what you mean about being printed on the board !
Many thanks

Kind regards

Graham
